rule:

    cnr_society_and_environment_major:
        rule: AND
        args: 
            - university_all
            - cnr_upper_division
            - AND: # Lower-Div
                - cnr_espm_environmental_science_core
                - cnr_espm_social_science_core
                - OR: # math
                    - course: MATH.1A
                    - course: MATH.10A
                    - course: MATH.16A
                    - course: STAT.2
                    - course: STAT.20
                    - course: PB HLTH.140
                    - course: PB HLTH.142
                - OR: # econ
                    - course: ENVECON.1
                    - course: ECON.C3
                    - course: ECON.1
                    - course: ECON.2
            - AND: # Five Course Breadth
                - cnr_breadth_arts_history_philosophy
                - ls_breadth_physical
                - ls_breadth_biological
                - ls_breadth_international
                - ls_breadth_social
            - AND: # upper-div
                - OR: # enviro or political economics
                    - course: POL SCI.126A
                    - course: POL SCI.139B
                    - course: GEOG.C110
                    - course: GEOG.C112
                    - course: GEOG.156
                    - course: DEV STD.C100
                    - course: ECON.C125
                    - course: ENVECON.100
                    - course: ENVECON.C101
                    - course: ENVECON.131
                    - course: ENVECON.140AC
                    - course: ENVECON.153
                    - course: ENVECON.161
                    - course: ENVECON.C180
                    - course: ENE,RES.C180
                    - course: ISF.C101
                    - course: POLECON.100
                    - course: POLECON.101
                    - course: GPP.115
                    - course: IAS.115
                    - course: PUB POL.C103
                - course: ESPM.194B
            - OR: # Area of concentration requirement
                - AND: # US Environmental Policy and Management
                    - OR: # primary core course
                        - course: ESPM.102C
                        - course: ESPM.102D
                        - course: ESPM.160AC
                        - course: ESPM.161
                        - course: ESPM.186
                        - course: ESPM.C191
                    - numcourses: # primary area of concentration
                        min: 4
                        courses:
                            - cnr_society_and_environment_area_us_environmental_policy_and_management
                    - AND: # other concentrations
                        - numcourses:
                            min: 3
                            courses:
                                - AND: # global environmental politics
                                    - numcourses:
                                        min: 1
                                        courses:
                                            - cnr_society_and_environment_area_global_environmental_politics
                                - AND: # justice and sustainability
                                    - numcourses:
                                        min: 1
                                        courses:
                                            - cnr_society_and_environment_area_justice_and_sustainability

                - AND: # global environmental politics
                    - OR: # primary core course
                        - course: ESPM.151
                        - course: ESPM.162
                        - course: ESPM.165
                        - course: ESPM.168
                        - course: ESPM.169
                    - numcourses: # primary area of concentration
                        min: 4
                        courses:
                            - cnr_society_and_environment_area_global_environmental_politics
                    - AND: # other concentrations
                        - numcourses:
                            min: 3
                            courses:
                                - AND: # us environmental policy and management
                                    - numcourses:
                                        min: 1
                                        courses:
                                            - cnr_society_and_environment_area_us_environmental_policy_and_management
                                - AND: # justice and sustainability
                                    - numcourses:
                                        min: 1
                                        courses:
                                            - cnr_society_and_environment_area_justice_and_sustainability
                - AND: # justice and sustainability
                    - OR: # primary core course
                        - course: ESPM.117
                        - course: ESPM.155
                        - course: ESPM.163AC
                        - course: ESPM.166
                        - course: ESPM.C167
                    - numcourses: # primary area of concentration
                        min: 4
                        courses:
                            - cnr_society_and_environment_area_justice_and_sustainability
                    - AND: # other concentrations
                        - numcourses:
                            min: 3
                            courses:
                                - AND: # us environmental policy and management
                                    - numcourses:
                                        min: 1
                                        courses:
                                            - cnr_society_and_environment_area_us_environmental_policy_and_management
                                - AND: # global environmental politics
                                    - numcourses:
                                        min: 1
                                        courses:
                                            - cnr_society_and_environment_area_global_environmental_politics





