rule:

	cnr_society_and_environment_major:
	    rule: AND
	    args: 
	    	- university_all
            - AND:
                - units:
                    min: 15
                    dept:
                        - dept: AGR CHM
                        - dept: ENE,RES
                        - dept: ESPM
                        - dept: NUSCTX
                        - dept: PLANTBI
	    	- AND: # lower division
				- OR: # espm environmental science core
					- course: ESPM.2
					- course: ESPM.6
					- course: ESPM.C10
					- course: LNS.C30V
					- course: ESPM.15
				- OR: # espm social science core
					- course: ESPM.C11
					- coruse: LNS.C30U
					- course: ESPM.C12
					- course: ENGLISH.C77
					- course: ESPM.50AC
					- course: ESPM.60
				- OR: # math
					- course: MATH.1A
					- course: MATH.10A
					- course: 
			- AND: # Five Course Breadth
				- OR:
					- units:
						min: 3
						courses:
							- ls_breadth_social
				- OR:
					- units:
						min: 3
						courses:
							- ls_breadth_international
				- OR:
					- units:
						min: 3
						courses:
							- ls_breadth_physical
				- OR:
					- units:
						min: 3
						courses:
							- ls_breadth_arts
							- ls_breadth_history
							- ls_breadth_philosophy
				- OR:
					- units:
						min: 3
						courses:
							- ls_breadth_biological