rules: # i don't understand this major at all

    ced_social_cultural_factors_environmental_design_minor:
        description: "Social and Cultural Factors in Environmental Design Minor"
        rule: AND
        args:
            - rule: social_cultural_factors_environmental_design_minor_prereqs
            - rule: social_cultural_factors_environmental_design_minor_required

    ced_social_cultural_factors_environmental_design_minor_prereqs:
        description: "Social and Cultural Factors in Environmental Design Minor Prerequisites"
        rule: OR
        args:
            - course: ENV DES.1
            - course: ENV.DES4

    ced_social_cultural_factors_environmental_design_minor_required:
        description: "Social and Cultural Factors in Environmental Design Minor Required Courses"
        rule: OR
        args:
            - rule: social_cultural_factors_environmental_design_minor_required_arch_majors
            - rule: social_cultural_factors_environmental_design_minor_required_urban_majors
            - rule: social_cultural_factors_environmental_design_minor_required_other

    ced_social_cultural_factors_environmental_design_minor_required_arch_majors:
        description: "Social and Cultural Factors in Environmental Design Minor for Architecture Majors"
        rule: AND
        args:
            - course: ARCH.110
            - course: CY PLAN.115
            # also four area studies courses or three area courses for major
            # two classes in 110 series to cover minor reqs...?

    ced_social_cultural_factors_environmental_design_minor_required_ced_courses:
        description: "So and Cultural Factors in Environmental Design Minor: CED Courses"
        rule: count_courses
        args:
            min: 3
            rule: OR
            args:
                - course: ARCH.130
                - course: ARCH.179 # non-western arch section
                - course: CY PLAN.110
                - course: ENV DES.C169A
                - course: ENV DES.C169B
                - course: LD ARCH.130
                - course: CY PLAN.118AC
                - course: CY PLAN.190
                - course: CY PLAN.111
                - course: LD ARCH.138AC
                - course: LD ARCH.141AC

# ARCH 110 (3) Social and Cultural Factors in Design. Architecture majors: To complete the major and this minor, complete four area studies courses or three area studies for the major and two classes in the ARCH 110 series to cover minor requirements 1 and 4.
# CY PLAN 115 (3) Urbanization in Developing Countries. Urban studies majors: Complete an additional class in the ARCH 110 series.



