rules:

    coe_environmental_engineering_science_major:
        description: "Environmental Engineering Science Major"
        rule: AND
        args:
            - rule: coe_humanities_and_social_sciences
            - rule: coe_lowerdiv_environmental_engineering
            - rule: coe_upperdiv_environmental_engineering
            - rule: units_upperdiv
            - rule: units_total


    coe_lowerdiv_environmental_engineering:
        description: "Environmental Engineering Lower Division"
        rule: AND
        args:
            - rule: chem1_4a
            - course: ENGIN.7
            - course: MATH.1A
            - course: MATH.1B
            - course: MATH.53
            - course: MATH.54
            - course: PHYSICS.7A
            - course: PHYSICS.7B
            - course: PHYSICS.7C
            - course: BIOLOGY.1B
            - rule: civec30_mecec85
            - course: CIV ENG.111
            - rule: enviro_eng_science_electives

    enviro_eng_science_electives:
        hidden: true
        rule: count_courses
            min: 3
            rule: OR
            args:
                - rule: bio1a
                - course: CHEM.1B
                - rule: chem3a
                - course: CHEM.3B
                - course: CHEM.4B
                - course: PHYSICS.7C
                - course: EPS.50

    coe_upperdiv_environmental_engineering:
        description: "Environmental Engineering Upper Division"
        rule: AND
        args:
            - rule: env_eng_math
            - rule: env_eng_env_fluid
            - rule: env_eng_fluid_mechanics
            - rule: env_eng_mechanics
            - rule: env_eng_thermodynamics
            - rule: env_eng_cluster
            - rule: env_eng_science

    env_eng_math:
        hidden: true
        rule: OR
        args:
            - rule: math121
            - rule: math110_128a
            - rule: stat134_135
            - rule: e117_177

    math121:
        hidden: true
        rule: AND
        args:
            - course: MATH.121A
            - course: MATH.121B

    math110_128a:
        hidden: true
        rule: AND
        args:
            - course: MATH.110
            - course: MATH.128A

    stat134_135:
        hidden: true
        rule: AND
        args:
            - course: STAT.134
            - course: STAT.135

    e117_177:
        hidden: true
        rule: AND
        args:
            - course: ENGIN.117
            - course: ENGIN.177

    env_eng_env_fluid:
        hidden: true
        rule: OR
        args:
            - course: CIV ENG.101
            - course: CIV ENG.103
            - course: CIV ENG.173
            - course: EPS.105
            - course: EPS.C129
            - course: ESPM.C129
            - course: ESPM.181

    env_eng_fluid_mechanics:
        hidden: true
        rule: OR
        args:
            - course: CIV ENG.100
            - course: ENGIN.150A
            - course: MEC ENG.106

    env_eng_mechanics:
        hidden: true
        rule: OR
        args:
            - course: CIV ENG.130N
            - course: MEC ENG.104

    env_eng_thermodynamics:
        hidden: true
        rule: OR
        args:
            - course: CHM ENG.141
            - course: ENGIN.115
            - course: MEC ENG.40

    env_eng_cluster:
        hidden: true
        rule: OR
        args:
            - rule: env_eng_bio
            - rule: env_eng_ecology
            - rule: env_eng_energy
            - rule: env_eng_geo
            - rule: env_eng_policy
            - rule: env_eng_process
            - rule: env_eng_resources

    env_eng_bio:
        hidden: true
        rule: units
            min: 12
            rule: OR
            args:
                - rule: mcbc112
                - course: MCELLBI.113
                - course: MCELLBI.C114
                - course: MCELLBI.C116
                - course: MCELLBI.130A
                - course: MCELLBI.133L
                - course: PLANTBI.120
                - course: PLANTBI.120L
                - course: PLANTBI.150
                - course: PLANTBI.150L
                - course: PLANTBI.180

    env_eng_ecology:
        hidden: true
        rule: units
            min: 12
            rule: OR
            args:
                - course: ESPM.C103
                - course: ESPM.C104
                - course: INTEGBI.149
                - course: INTEGBI.151
                - course: INTEGBI.151L
                - course: INTEGBI.152
                - course: INTEGBI.153
                - course: INTEGBI.153LF
                - course: INTEGBI.154
                - course: INTEGBI.154L
                - course: INTEGBI.162
                - course: INTEGBI.166

    env_eng_energy:
        hidden: true
        rule: units
            min: 12
            rule: OR
            args:
                - course: ARCH.140
                - course: CIV ENG.C106
                - course: CIV ENG.107
                - course: CIV ENG.108
                - course: EL ENG.134
                - course: EL ENG.137A
                - course: EL ENG.137B
                - course: ENE,RES.280
                - course: MAT SCI.136
                - course: MEC ENG.109
                - course: MEC ENG.140
                - course: MEC ENG.146
                - course: NUC ENG.161

    env_eng_geo:
        hidden: true
        rule: units
            min: 12
            rule: OR
            args:
                - course: CIV ENG.171
                - course: CIV ENG.172
                - course: CIV ENG.173
                - course: CIV ENG.175
                - course: CIV ENG.176
                - course: CIV ENG.C178
                - course: CIV ENG.281

    env_eng_policy:
        hidden: true
        rule: units
            min: 12
            rule: OR
            args:
                - course: ECON.C103
                - course: ECON.104
                - course: ECON.126
                - course: ECON.141
                - course: ECON.C142
                - course: POL SCI.C131A
                - course: SOCIOL.105
                - course: SOCIOL.106

    env_eng_process:
        hidden: true
        rule: units
            min: 12
            rule: OR
            args:
                - course: CHM ENG.140
                - course: CHM ENG.142
                - course: CHM ENG.150B
                - course: CHM ENG.154
                - course: CHM ENG.170A
                - course: CHM ENG.170B
                - course: CHM ENG.170L
                - course: CHM ENG.171

    env_eng_resources:
        hidden: true
        rule: units
            min: 12
            rule: OR
            args:
                - course: CIV ENG.101
                - course: CIV ENG.103
                - course: CIV ENG.107
                - course: CIV ENG.113
                - course: CIV ENG.114
                - course: CIV ENG.115
                - course: EPS.C180
                - course: ESPM.128
                - course: MEC ENG.140
                - course: NUC ENG.124

    env_eng_science:
        hidden: true
        rule: OR
        args:
            - rule: env_eng_orgo
            - rule: env_eng_chem
            - rule: env_eng_eps
            - rule: env_eng_eps_geog
            - rule: env_eng_espm
            - rule: env_eng_mcb

    env_eng_orgo:
        hidden: true
        rule: units
            min: 8
            rule: OR
            args:
                - course: CHEM.112A
                - course: CHEM.112B
                - course: CHEM.3A
                - course: CHEM.3B

    env_eng_chem:
        hidden: true
        rule: units
            min: 8
            rule: OR
            args:
                - course: CHEM.120A
                - course: CHEM.120B
                - course: CHEM.125

    env_eng_eps:
        hidden: true
        rule: units
            min: 8
            rule: OR
            args:
                - course: EPS.101
                - course: EPS.105
                - course: EPS.108
                - course: EPS.116
                - course: EPS.117
                - course: EPS.124
                - course: EPS.C146

    env_eng_eps_geog:
        hidden: true
        rule: units
            min: 8
            rule: OR
            args:
                - course: EPS.C180
                - course: EPS.181
                - course: EPS.182
                - course: GEOG.142

    env_eng_espm:
        hidden: true
        rule: units
            min: 8
            rule: OR
            args:
                - course: ESPM.102A
                - course: ESPM.C103
                - course: ESPM.111
                - course: ESPM.112
                - course: ESPM.120
                - course: ESPM.126
                - course: ESPM.C128
                - course: ESPM.131

    env_eng_mcb:
        hidden: true
        rule: units
            min: 8
            rule: OR
            args:
                - course: MCB.102
                - course: MCB.112
                - course: MCB.112L



