rules:

    ced_sustainable_environmental_design_major:
        description: "Sustainable Environmental Design Major"
        rule: AND
        args:
            - university_all
            - ced_breadth_all
            - ced_lowerdiv_environmental_design
            - ced_lowerdiv_sustainable_environmental_design_requirements
            - ced_core_upperdiv_sustainable_environmental_design_requirements
            - units_total


    # to define the major
    ced_lowerdiv_sustainable_environmental_design_requirements:
        description: "Lower Division Sustainable Environmental Design Requirements"
        rule: AND
        args:
            - course: LD ARCH.12
            - OR:
                - course: MATH.16A
                - course: MATH.1A
                # or higher
            - OR:
                - course: STAT.2
                - course: STAT.20
                - course: STAT.21
                # or higher
            - OR:
                - course: PHYSICS.7A
                - course: PHYSICS.8A
            - OR:
                - course: ECON.1
                - course: ECON.2
                - course: ECON.C3
                - course: ENVECON.C3

    ced_core_upperdiv_sustainable_environmental_design_requirements: # don't fulfill breadth
        description: "Upper Division Core Requirements"
        rule: AND
        args:
            - course: ENV DES.100
            - course: ENV DES.102
            - course: ENV DES.106
            - course: ARCH.140
            - course: ARCH.242
            - course: CY PLAN.119
            - course: LD ARCH.110
            - course: LD ARCH.130
            - course: LD ARCH.188
            - course: GEOG.188

    ced_area_upperdiv_sustainable_environmental_design_requirements: # don't fulfill breadth
        description: "Sustainable Environmental Design Area Requirements"
        rule: count_courses
        args: # unsure of rule structure here
            min: 4
            rule: OR
            args:
                min: 4
                rule: AND
                args:
                    - ced_sustainable_environmental_design_economics_area
                    - ced_sustainable_environemental_design_society_area
                    - ced_sustainable_environmental_design_resources_area
                    - ced_sustainable_environmental_design_design_area
                min: 2
                rule: OR
                args:
                    - ced_sustainable_environmental_design_economics_area
                min: 2
                rule: OR
                args:
                    - ced_sustainable_environmental_design_society_area
                min: 2
                rule: OR
                args:
                    - ced_sustainable_environmental_design_design_area
                min: 2
                rule: OR
                args:
                    - ced_sustainable_environmental_design_resources_area


    ced_sustainable_environmental_design_economics_area:
        description: "CED Sustainable Environmental Design Major Economics, Business and Policy Area"
        rule: same_course
        args:
            - OR:
                - course: UGBA.107
                - course: UGBA.180
                - course: CY PLAN.113A
                - course: CY PLAN.113B
                - course: CY PLAN.115
                - course: IAS.115
                - course: GPP.115
                - course: ENVECON.100
                - course: ENVECON.C175
                - course: IAS.C175
                - course: ENE,RES.151
                - course: ENE,RES.190
                - course: ESPM.60
                - course: ESPM.166
                - course: ESPM.168
                - course: ESPM.169
                - course: ESPM.193A
                - course: EDUC.C193A
                - course: PUB POL.182

    ced_sustainable_environmental_design_society_area:
        description: "CED Sustianable Environmental Design Major Society, Culture and Ethics Area"
        rule: same_course
        args:
            - OR:
                - course: ANTHRO.137
                - course: ARCH.110AC
                - course: ARCH.133
                - course: CY PLAN.118AC
                - course: ENE,RES.100
                - course: ENE,RES.101
                - course: ESPM.148
                - course: ESPM.151
                - course: ESPM.161
                - course: ESPM.163AC
                - course: ESPM.C167
                - course: PB HLTH.C160
                - course: ESPM.155
                - course: LD ARCH.140
                - course: LD ARCH.141AC
                - course: SOCIOL.123
                - course: SOCIOL.128

    ced_sustainable_environmental_design_resources_area:
        description: "CED Sustainable Environmental Design Major Resources and Environmental Management Area"
        rule: same_course
        args:
            - OR:
                - course: ENE,RES.102
                - course: EPS.170AC
                - course: ESPM.50AC
                - course: ESPM.102D
                - course: ESPM.102C
                - course: ESPM.117
                - course: INTEGBI.152

    ced_sustainable_environmental_design_design_area:
        description: "CED Sustainable Environmental Design Major Design and Technology Area"
        rule: same_course
        args:
            - OR:
                - course: ARCH.105
                - course: ARCH.122
                - course: ARCH.130
                - course: ARCH.242
                - course: ARCH.149
                - course: ARCH.249
                - course: ARCH.160
                - course: CY PLAN.C111
                - course: ARCH.C111
                - course: CY PLAN.C114
                - course: CIV ENG.C114
                - course: CY PLAN.116
                - course: CY PLAN.140
                - course: ENE,RES.175
                - course: ENV DES.11A
                - course: ENV DES.11B
                - course: GEOG.125
                - course: INFO.146

